#!/usr/bin/env bash

XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
BGDIR=${BGDIR:-$HOME/backgrounds}
BGSTATE=${BGSTATE:-${XDG_DATA_HOME}/feh-random-background}
EXTENSIONS=${BGEXTENSIONRE:-"png\|jpg\|jpeg\|gif\|tiff"}

mkdir -p "$BGSTATE"

refill() {
    if [ ! -s "$BGSTATE/next" ]; then
      find -L "$BGDIR" -type f -iregex ".*\.\($EXTENSIONS\)" -print0 | shuf -z > "$BGSTATE/next"
      if [ ! -s "$BGSTATE/next" ]; then
        echo "No background images to choose from"
        exit 1
      fi
    fi
}

refill

BGFILE="$(sed -z '1q' < "$BGSTATE/next" | tr -d '\0')"
sed -z '1d' -i "$BGSTATE/next"

cat >"$BGSTATE/current" <<EOF
#!$SHELL
BGFILE=$(printf "%q" "$BGFILE")
$@
EOF
chmod +x "$BGSTATE/current"
"$BGSTATE/current"
EXIT="$?"

refill

exit "$EXIT"
