#!/bin/sh

BGDIR=${BGDIR:-$HOME/backgrounds}
BGSTATE=${BGSTATE:-$HOME/.feh-random-background}

if [ ! -s "$BGSTATE" ]; then
  find -L "$BGDIR" -type f -print0 | shuf -z > "$BGSTATE"
  if [ "$(wc -c < "$BGSTATE")" -eq 0 ]; then
    echo "No background images to choose from"
    exit 1
  fi
fi

next_background() {
  # Will complain about the terminating null-character, but it won't affect it
  BGFILE="$(sed -z '1q' < "$BGSTATE" | sed 's/\x0.*//')"
  sed -z '1d' -i "$BGSTATE"
  if [ ! -e "$BGFILE" ]; then
    return 1
  else
    feh "$@" "$BGFILE"
    return "$?"
  fi
}

# Drop non-background files
while ! next_background "$@"; do :; done
